test-1:
	./run.sh 1 web-BerkStan.txt

test-2:
	./run.sh 2 web-BerkStan.txt

test-3:
	./run.sh 3 web-BerkStan.txt

run-all-web:
	make test-1
	make test-2
	make test-3

test-wiki:
	./run.sh 1 enwiki-pages-articles

run-all-wiki:
	./run.sh 1 enwiki-pages-articles
	./run.sh 2 enwiki-pages-articles
	./run.sh 3 enwiki-pages-articles
